- name: Create and apply ACL for Requirement 1
  hosts: R2
  tasks:
    - name: Load new ACL into device
      ios_config:
        lines:
          - ip access-list extended REQ1
          - 10 deny tcp any any eq telnet
          - 20 permit ip any any
    - name: Apply new ACL to R2 Eth0/1 out
      ios_config:
        lines:
          - ip access-group REQ1 out
    - name: Check result
      ios_command:
        commands:
          - show ip access-lists REQ1
      register: acl_result
    - name: Print Result
      debug:
        var: acl_result.stdout_lines
